server:
  port: 8080 # The Entry Point

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # This URL is where Gateway checks if the token is valid
          issuer-uri: http://localhost:8180/realms/sales-store

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true # Automatically find services in Eureka
          routes:
            # Route logic: If path is /api/v1/products, go to Product Service
            - id: product-service
              uri: lb://product-service # "lb" means Load Balanced via Eureka
              predicates:
                - Path=/api/v1/products/**, /api/v1/categories/**, /api/v1/variants/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/