server:
  port: 8083

spring:
  config:
    activate:
      on-profile: local
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      linger-ms: 0
      request-timeout-ms: 30000
      delivery-timeout-ms: 30000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
      template:
        observation-enabled: true

  management:
    tracing:
      sampling:
        probability: 1.0 # 1.0 means log 100% of requests (0.1 means 10%)
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

resilience4j:
  circuitbreaker:
    instances:
      inventory: # This name matches the annotation in the code
        registerHealthIndicator: true
        slidingWindowSize: 10 # Check last 10 calls
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s # Wait 5 seconds before trying again
        failureRateThreshold: 50 # Trip if 50% of calls fail
        eventConsumerBufferSize: 10

  retry:
    instances:
      inventory:
        maxAttempts: 3 # Try 3 times before giving up
        waitDuration: 1s # Wait 1 second between retries
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/