server:
  port: 8082 # Port according to your Serials

spring:
  config:
      activate:
        on-profile: local
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      linger-ms: 0
      request-timeout-ms: 30000
      delivery-timeout-ms: 30000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
      template:
        observation-enabled: true

  management:
    tracing:
      sampling:
        probability: 1.0 # 1.0 means log 100% of requests (0.1 means 10%)
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/