server:
  port: 8081 # Product Service runs on 8081

spring:
  config:
    activate:
      on-profile: local

  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5434/product_db
    username: postgres
    password: password # Change this
  jpa:
    hibernate:
      ddl-auto: update # Change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  cache:
    type: redis
    redis :
      host: localhost
      port: 6379
      time-to-live: 600000


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: products

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/