server:
  port: 8081 # Product Service runs on 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: postgres
    password: product # Change this
  jpa:
    hibernate:
      ddl-auto: update # Change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true