server:
  port: 8084

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: ai-service

  datasource:
    url: jdbc:postgresql://salesstore-vector-db:5432/vector_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  ai:
    ollama:
      base-url: http://salesstore-ollama:11434
      embedding:
        model: nomic-embed-text # High performance embedding model
    vectorstore:
      pgvector:
        index-type: HNSW # High-speed search index
        distance-type: COSINE_DISTANCE
        dimensions: 768 # Match nomic-embed-text dimensions

  kafka:
    bootstrap-servers: salesstore-kafka:9092
    producer:
      retries: 3
      properties:
        delivery.timeout.ms: 3000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      observation-enabled: true
    template:
      observation-enabled: true

  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://salesstore-zipkin:9411/api/v2/spans